[package]
name = "wintun-security"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
license = "Apache-2.0"
publish = false

[target.'cfg(target_os = "windows")'.dependencies]
anyhow = "1.0.98"
rand = "0.10.0"
sha2 = "0.11.0"
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_Security_Cryptography",
    "Win32_Security_Cryptography_Catalog",
    "Win32_Security_Cryptography_Sip",
    "Win32_Security_WinTrust",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_System_WindowsProgramming",
    "Win32_UI_Shell",
] }
